name: STIS soupisky export
on:
  workflow_dispatch:
    inputs:
      rocnik:
        description: 'Rocnik (default 2025)'
        required: false
  schedule:
    - cron: '7 4,12,20 * * *'   # 3× denně (UTC)

permissions:
  contents: write

concurrency:
  group: stis-soupisky
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.55.0-jammy
    steps:
      - uses: actions/checkout@v4

      - name: Install Playwright (pip) + browser
        run: |
          python -V
          pip install --no-cache-dir playwright==1.55.0
          python - << 'PY'
          import importlib.metadata as im
          print("playwright", im.version("playwright"))
          PY
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          ROCNIK: ${{ inputs.rocnik || '2025' }}
        run: python scrape_soupisky.py

      - name: Upload debug (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: data/debug/*
          if-no-files-found: ignore

      - name: Commit CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          git diff --cached --quiet || git commit -m "Update CSV [skip ci]"
          git push || true
